from pathlib import Path

path = Path("downloader/browser_media_resolver.py")
text = path.read_text(encoding="utf-8")
old = '''async def resolve(url: str, *, validator, timeout_ms: int = DEFAULT_TIMEOUT_MS, settle_ms: int = DEFAULT_SETTLE_MS, max_candidates: int = DEFAULT_MAX_CANDIDATES, max_pages: int = DEFAULT_MAX_PAGES) -> list[str]:\n    """Resolve browser media asynchronously so it can run inside the bot event loop."""\n    if not _browser_enabled():\n        return []\n    try:\n        if _is_krx18_host(url):\n            started = asyncio.get_running_loop().time()\n            try:\n                return await asyncio.wait_for(\n                    _resolve_async(\n                        url,\n                        validator=validator,\n                        timeout_ms=timeout_ms,\n                        settle_ms=settle_ms,\n                        max_candidates=max_candidates,\n                        max_pages=max_pages,\n                    ),\n                    timeout=KRX18_HARD_BUDGET_SECONDS,\n                )\n            except asyncio.TimeoutError:\n                elapsed = asyncio.get_running_loop().time() - started\n                LOG.warning("KRX18 browser resolver hard budget exhausted after %.1fs", elapsed)\n                print(f"⏱️ KRX18 Browser Resolver: hard budget exhausted after {elapsed:.1f}s", flush=True)\n                return []\n        return await _resolve_async(\n            url,\n            validator=validator,\n            timeout_ms=timeout_ms,\n            settle_ms=settle_ms,\n            max_candidates=max_candidates,\n            max_pages=max_pages,\n        )\n    except asyncio.CancelledError:\n        raise\n    except Exception as exc:\n        LOG.warning("Browser resolver failed: %s", type(exc).__name__)\n        print(f"⚠️ Browser resolver failed: {type(exc).__name__}", flush=True)\n        return []\n'''
new = '''async def resolve(url: str, *, validator, timeout_ms: int = DEFAULT_TIMEOUT_MS, settle_ms: int = DEFAULT_SETTLE_MS, max_candidates: int = DEFAULT_MAX_CANDIDATES, max_pages: int = DEFAULT_MAX_PAGES) -> list[str]:\n    """Resolve browser media asynchronously so it can run inside the bot event loop."""\n    if not _browser_enabled():\n        return []\n    try:\n        if _is_krx18_host(url):\n            # KRX18 is handled by the dedicated public-page resolver.\n            # Do not fall back to generic browser exploration here: that path\n            # was both slow and capable of accepting unrelated media.\n            from downloader.krx18_resolver import resolve_media\n            return await resolve_media(url, validator=validator, max_candidates=max_candidates)\n        return await _resolve_async(\n            url,\n            validator=validator,\n            timeout_ms=timeout_ms,\n            settle_ms=settle_ms,\n            max_candidates=max_candidates,\n            max_pages=max_pages,\n        )\n    except asyncio.CancelledError:\n        raise\n    except Exception as exc:\n        LOG.warning("Browser resolver failed: %s", type(exc).__name__)\n        print(f"⚠️ Browser resolver failed: {type(exc).__name__}", flush=True)\n        return []\n'''
if old not in text:
    raise SystemExit("expected KRX18 resolve block not found")
path.write_text(text.replace(old, new), encoding="utf-8")
