from pathlib import Path

BOT = Path("bot.py")
MARKER = "# ALIBOT_ADMIN_CONTROL_CENTER_V1"


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected 1 match, found {count}")
    return text.replace(old, new, 1)


def main():
    text = BOT.read_text(encoding="utf-8")
    if MARKER in text:
        print("Admin Control Center already applied")
        return

    old_keyboard = '''def admin_keyboard():\n    return InlineKeyboardMarkup([\n        [\n            InlineKeyboardButton(\n                "📊 لوحة المعلومات",\n                callback_data="admin_dashboard_30"\n            )\n        ],\n        [\n            InlineKeyboardButton(\n                "📈 الإحصائيات",\n                callback_data="admin_stats"\n            ),\n            InlineKeyboardButton(\n                "👥 المستخدمون",\n                callback_data="admin_users_0"\n            ),\n        ],\n        [\n            InlineKeyboardButton(\n                "📢 إرسال إعلان",\n                callback_data="admin_broadcast"\n            )\n        ],\n        [\n            InlineKeyboardButton(\n                "🤖 الذكاء الاصطناعي",\n                callback_data="admin_ai"\n            )\n        ],\n        [\n            InlineKeyboardButton(\n                "🗑️ مسح الإعلانات المرسلة",\n                callback_data="admin_delete_broadcasts"\n            )\n        ],\n        [\n            InlineKeyboardButton(\n                "🧹 تفريغ ذاكرة التخزين",\n                callback_data="admin_storage"\n            )\n        ],\n    ])\n'''

    new_keyboard = '''def admin_keyboard():\n    return InlineKeyboardMarkup([\n        [\n            InlineKeyboardButton("📊 مركز التحكم", callback_data="admin_dashboard_30")\n        ],\n        [\n            InlineKeyboardButton("👥 المستخدمون", callback_data="admin_users_0"),\n            InlineKeyboardButton("📥 التحميلات", callback_data="admin_recent_downloads"),\n        ],\n        [\n            InlineKeyboardButton("📈 التحليلات", callback_data="admin_stats"),\n            InlineKeyboardButton("🌐 المنصات", callback_data="admin_top_websites"),\n        ],\n        [\n            InlineKeyboardButton("📢 الإذاعة", callback_data="admin_broadcast"),\n            InlineKeyboardButton("🤖 الذكاء الاصطناعي", callback_data="admin_ai"),\n        ],\n        [\n            InlineKeyboardButton("🚨 صحة النظام", callback_data="admin_health"),\n            InlineKeyboardButton("🧾 سجل الإدارة", callback_data="admin_audit"),\n        ],\n        [\n            InlineKeyboardButton("🛡️ الأمان", callback_data="admin_security"),\n            InlineKeyboardButton("🧹 التخزين", callback_data="admin_storage"),\n        ],\n    ])\n'''

    text = replace_once(text, old_keyboard, new_keyboard, "admin keyboard")

    db_anchor = '''    # --------------------------------------------------------\n    # جدول رسائل الإعلانات المرسلة\n    # --------------------------------------------------------\n'''
    db_insert = '''    # --------------------------------------------------------\n    # سجل عمليات الإدارة — append-only audit trail\n    # --------------------------------------------------------\n    cur.execute("""\n        CREATE TABLE IF NOT EXISTS admin_audit_logs (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            admin_id INTEGER NOT NULL,\n            action TEXT NOT NULL,\n            target_id INTEGER,\n            details TEXT,\n            created_at TEXT NOT NULL\n        )\n    """)\n\n    cur.execute("""\n        CREATE INDEX IF NOT EXISTS idx_admin_audit_created_at\n        ON admin_audit_logs(created_at)\n    """)\n\n    cur.execute("""\n        CREATE INDEX IF NOT EXISTS idx_admin_audit_admin_id\n        ON admin_audit_logs(admin_id)\n    """)\n\n'''
    text = replace_once(text, db_anchor, db_insert + db_anchor, "audit schema anchor")

    functions = r'''\n\n# ============================================================\n# AliBot Admin Control Center V1\n# ============================================================\n\nADMIN_CONTROL_CENTER_MARKER = "ALIBOT_ADMIN_CONTROL_CENTER_V1"\n\n\ndef admin_audit_log(admin_id, action, target_id=None, details=None):\n    """Write a bounded, non-secret administrative audit record."""\n    try:\n        safe_details = "" if details is None else str(details)[:1000]\n        conn = get_db()\n        conn.execute(\n            """\n            INSERT INTO admin_audit_logs\n                (admin_id, action, target_id, details, created_at)\n            VALUES (?, ?, ?, ?, ?)\n            """,\n            (\n                int(admin_id),\n                str(action)[:200],\n                target_id,\n                safe_details,\n                datetime.now().isoformat(),\n            ),\n        )\n        conn.commit()\n        conn.close()\n    except Exception as exc:\n        logger.warning("Admin audit log failed: %s", type(exc).__name__)\n\n\ndef _admin_health_snapshot():\n    """Collect lightweight health signals without touching downloader state."""\n    disk = shutil.disk_usage("/app")\n    db_ok = False\n    try:\n        conn = get_db()\n        conn.execute("SELECT 1")\n        conn.close()\n        db_ok = True\n    except Exception:\n        db_ok = False\n\n    return {\n        "database": db_ok,\n        "ffmpeg": bool(shutil.which("ffmpeg")),\n        "ffprobe": bool(shutil.which("ffprobe")),\n        "deno": bool(shutil.which("deno")),\n        "disk_free_gb": disk.free / (1024 ** 3),\n        "disk_total_gb": disk.total / (1024 ** 3),\n    }\n\n\nasync def admin_health_callback(update, context):\n    query = update.callback_query\n    await query.answer()\n    if update.effective_user.id != ADMIN_ID:\n        return\n\n    health = _admin_health_snapshot()\n    def mark(value):\n        return "🟢" if value else "🔴"\n\n    disk_status = "🟢 جيد" if health["disk_free_gb"] >= 1 else "🟠 منخفض"\n\n    text = (\n        "🚨 صحة النظام\\n"\n        "━━━━━━━━━━━━━━━━━━━━\\n\\n"\n        f"{mark(health['database'])} قاعدة البيانات\\n"\n        f"{mark(health['ffmpeg'])} FFmpeg\\n"\n        f"{mark(health['ffprobe'])} FFprobe\\n"\n        f"{mark(health['deno'])} Deno\\n\\n"\n        f"💾 المساحة الحرة: {health['disk_free_gb']:.2f} GB\\n"\n        f"📦 إجمالي التخزين: {health['disk_total_gb']:.2f} GB\\n"\n        f"📊 حالة التخزين: {disk_status}\\n\\n"\n        "ℹ️ هذه الفحوصات للقراءة فقط ولا تغيّر إعدادات البوت."
    )\n\n    await query.edit_message_text(\n        text,\n        reply_markup=InlineKeyboardMarkup([\n            [InlineKeyboardButton("🔄 تحديث", callback_data="admin_health")],\n            [\n                InlineKeyboardButton("🧾 سجل الإدارة", callback_data="admin_audit"),\n                InlineKeyboardButton("🔙 الرئيسية", callback_data="admin_home"),\n            ],\n        ]),\n    )\n\n\nasync def admin_audit_callback(update, context):\n    query = update.callback_query\n    await query.answer()\n    if update.effective_user.id != ADMIN_ID:\n        return\n\n    conn = get_db()\n    rows = conn.execute(\n        """\n        SELECT admin_id, action, target_id, details, created_at\n        FROM admin_audit_logs\n        ORDER BY id DESC\n        LIMIT 15\n        """\n    ).fetchall()\n    conn.close()\n\n    text = "🧾 سجل الإدارة\\n━━━━━━━━━━━━━━━━━━━━\\n\\n"\n    if not rows:\n        text += "لا توجد عمليات إدارية مسجلة بعد.\\n"\n    else:\n        for row in rows:\n            target = f" → {row['target_id']}" if row["target_id"] else ""\n            details = f" | {row['details']}" if row["details"] else ""\n            text += (\n                f"👑 {row['admin_id']} | {row['action']}{target}\\n"\n                f"🕐 {row['created_at']}{details}\\n"\n                "──────────────\\n"\n            )\n\n    await query.edit_message_text(\n        text[:3900],\n        reply_markup=InlineKeyboardMarkup([\n            [InlineKeyboardButton("🔄 تحديث", callback_data="admin_audit")],\n            [InlineKeyboardButton("🔙 الرئيسية", callback_data="admin_home")],\n        ]),\n    )\n\n\nasync def admin_security_callback(update, context):\n    query = update.callback_query\n    await query.answer()\n    if update.effective_user.id != ADMIN_ID:\n        return\n\n    admin_audit_log(ADMIN_ID, "view_security")\n    text = (\n        "🛡️ مركز الأمان\\n"\n        "━━━━━━━━━━━━━━━━━━━━\\n\\n"\n        "👑 المالك: مفعل\\n"\n        f"🆔 Owner ID: {ADMIN_ID}\\n\\n"\n        "🔐 الوصول الحالي: Owner-only\\n"\n        "🧾 سجل العمليات: مفعل\\n"\n        "🚫 لا توجد تغييرات صلاحيات تلقائية من هذه الشاشة.\\n\\n"\n        "📌 المرحلة التالية يمكن أن تضيف أدواراً منفصلة مثل Viewer / Moderator / Analyst مع صلاحيات دقيقة."
    )\n\n    await query.edit_message_text(\n        text,\n        reply_markup=InlineKeyboardMarkup([\n            [InlineKeyboardButton("🧾 سجل الإدارة", callback_data="admin_audit")],\n            [InlineKeyboardButton("🔙 الرئيسية", callback_data="admin_home")],\n        ]),\n    )\n\n\n# ============================================================\n# End AliBot Admin Control Center V1\n# ============================================================\n'''

    insertion_marker = "# بدء التشغيل\n\nif __name__ == \"__main__\":\n    main()"
    text = replace_once(text, insertion_marker, functions + "\n\n" + insertion_marker, "final insertion anchor")

    handler_anchor = '''    # ========================================================\n    # التحميل\n    # ========================================================\n'''
    handlers = '''    # ========================================================\n    # AliBot Admin Control Center V1\n    # ========================================================\n\n    app.add_handler(\n        CallbackQueryHandler(\n            admin_health_callback,\n            pattern=r"^admin_health$"\n        )\n    )\n\n    app.add_handler(\n        CallbackQueryHandler(\n            admin_audit_callback,\n            pattern=r"^admin_audit$"\n        )\n    )\n\n    app.add_handler(\n        CallbackQueryHandler(\n            admin_security_callback,\n            pattern=r"^admin_security$"\n        )\n    )\n\n'''
    text = replace_once(text, handler_anchor, handlers + handler_anchor, "handler anchor")

    # Log entry to the control center without changing download behavior.\n    dashboard_anchor = '''    await query.edit_message_text(\n        admin_dashboard_text(data),\n        reply_markup=admin_dashboard_keyboard(days)\n    )\n'''
    dashboard_logged = '''    admin_audit_log(ADMIN_ID, "view_dashboard", details=f"period={days}d")\n\n''' + dashboard_anchor
    text = replace_once(text, dashboard_anchor, dashboard_logged, "dashboard audit hook")

    text = MARKER + "\n" + text
    BOT.write_text(text, encoding="utf-8")
    print("Admin Control Center V1 applied successfully")


if __name__ == "__main__":\n    main()\n